[package]
name = "RustWebEngine"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = true  # Generování debug symbolů
opt-level = 0 # Bez optimalizací


[dependencies]
unicode-general-category = "1.0.0"
unicode-ident = "1.0.18"
num-bigint = "0.4.6"
